"""empty message

Revision ID: 48042eeafa1a
Revises: 501a0405112b
Create Date: 2023-10-31 20:56:52.439111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48042eeafa1a'
down_revision = '501a0405112b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)

    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BINARY(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('post_id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BINARY(length=16),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
