"""empty message

Revision ID: 438cdf390bb7
Revises: 21774ecc1d7e
Create Date: 2023-11-01 02:27:42.953833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438cdf390bb7'
down_revision = '21774ecc1d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_username_key', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('posts_username_key', ['username'])

    # ### end Alembic commands ###
